apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-python-shipdetector-onnx
  namespace: payload-app
  labels:
    app: app-python-shipdetector-onnx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-python-shipdetector-onnx
  template:
    metadata:
      labels:
        app: app-python-shipdetector-onnx
    spec:
      # Pod-level security context
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: app-python-shipdetector-onnx
        image: registry.spacefx.local:5000/app-python-shipdetector-onnx:0.11.0
        imagePullPolicy: Always
        # Container-level security context
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 1000
          capabilities:
            drop:
              - ALL
        env:
        - name: DOTNET_SYSTEM_GLOBALIZATION_INVARIANT
          value: "1"
        command: ["python"]
        args: ["/workspace/app-python-shipdetector-onnx/src/app/main.py"]
        volumeMounts:
        - name: tmp
          mountPath: /tmp
        - name: spacedev-data
          mountPath: /var/spacedev
      volumes:
      - name: tmp
        emptyDir: {}
      - name: spacedev-data
        emptyDir: {}